version: "3.8"
volumes:
  node-app-database-data:
    external: true
services:
  node-app-database:
    image: mongo:4.4.1
    container_name: node-app-database
    command: [--auth]
    env_file:
      - .env
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - node-app-database-data:/data/db
      - ./docker/mongo/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
    restart: always
