version: "3.8"
volumes:
  node-app-database-data:
    external: true
services:
  node-app-mongodb:
    image: mongo:4.4.1
    container_name: node-app-mongodb
    command: [--auth]
    env_file:
      - .env
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - node-app-database-data:/data/db
      - ./docker/mongo/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
    restart: always

  node-app-mongoku:
    image: huggingface/mongoku:1.3.0
    container_name: node-app-mongoku
    depends_on:
      - node-app-mongodb
    ports:
      - ${MONGOKU_PORT}:3100
    environment:
      MONGOKU_DEFAULT_HOST: "${MONGO_USERNAME}:${MONGO_PASSWORD}@node-app-mongodb:${MONGO_PORT}"
    env_file:
      - .env
    restart: always
